{% set name = "pygff" %}
{% set version = "0.0.2" %}
{% set sha256 = "39b92b4394b63df84287b14e4dd842e812a9acee0c5663910b0c8e083a90d301" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - numpy 
    - pandas >0.23.*
  run:
    - python >={{ python_min }}
    - {{ pin_compatible('numpy') }}
    - pandas >0.23.*

test:
  requires:
    - python {{ python_min }}
  imports:
    - pygff

about:
  home: https://github.com/betteridiot/pygff
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'GFF3 reader designed for educational use at the University of Michigan, Department of Computational Medicine & Bioinformatics'

extra:
  recipe-maintainers:
    - betteridiot
